name: Swift

on: [push]

jobs:
  build:

    runs-on: [macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v